"""Primera migración

Revision ID: 1b73cc77715a
Revises: 
Create Date: 2025-06-25 17:17:02.503384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b73cc77715a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usu', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_usu', sa.String(length=255), nullable=False),
    sa.Column('correo_usu', sa.String(length=100), nullable=False),
    sa.Column('contrasena_hash_usu', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro_usu', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('intereses', sa.String(length=255), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('institucion', sa.String(length=255), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('ultima_actividad', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usu'),
    sa.UniqueConstraint('correo_usu'),
    sa.UniqueConstraint('firebase_uid'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('visit_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_visits', sa.Integer(), nullable=True),
    sa.Column('projects_visits', sa.Integer(), nullable=True),
    sa.Column('contact_visits', sa.Integer(), nullable=True),
    sa.Column('news_visits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noticias',
    sa.Column('id_noticia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo_noticia', sa.String(length=255), nullable=False),
    sa.Column('categoria_noticia', sa.String(length=100), nullable=False),
    sa.Column('descripcion_noticia', sa.Text(), nullable=True),
    sa.Column('contenido_noticia', sa.Text(), nullable=False),
    sa.Column('imagen_url_noticia', sa.String(length=500), nullable=True),
    sa.Column('public_id_noticia', sa.String(length=255), nullable=True),
    sa.Column('es_publicada', sa.Enum('publicada', 'archivada', 'eliminada', name='estadonoticia'), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id_usu'], ),
    sa.PrimaryKeyConstraint('id_noticia')
    )
    op.create_table('proyectos',
    sa.Column('id_proyecto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo_proyecto', sa.String(length=255), nullable=False),
    sa.Column('categoria_proyecto', sa.String(length=100), nullable=True),
    sa.Column('estado_proyecto', sa.Enum('En Progreso', 'Finalizado', 'Planeado'), nullable=True),
    sa.Column('anio_proyecto', sa.Integer(), nullable=False),
    sa.Column('participantes_proyecto', sa.Integer(), nullable=True),
    sa.Column('descripcion_proyecto', sa.Text(), nullable=True),
    sa.Column('metodologiauno_proyecto', sa.Text(), nullable=True),
    sa.Column('metodologiados_proyecto', sa.Text(), nullable=True),
    sa.Column('areas_proyecto', sa.Text(), nullable=True),
    sa.Column('imagenurl_proyecto', sa.String(length=255), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usu'], ),
    sa.PrimaryKeyConstraint('id_proyecto')
    )
    op.create_table('testimonios',
    sa.Column('id_tes', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usu_tes', sa.Integer(), nullable=True),
    sa.Column('contenido_tes', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion_tes', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('estado_tes', sa.Enum('aprobado', 'anulado', 'en espera'), nullable=False),
    sa.Column('titulo_tes', sa.String(length=100), nullable=False),
    sa.Column('cargo_tes', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usu_tes'], ['usuarios.id_usu'], ),
    sa.PrimaryKeyConstraint('id_tes')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonios')
    op.drop_table('proyectos')
    op.drop_table('noticias')
    op.drop_table('visit_stats')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
